package com.we.config;

/**
 * Created by 74234 on 2017/4/23.
 */

public interface ConfigReceiveAddress {
    //RXBUS传递的收貨地址
    int RECEIVEADDRESS_RX_SEND_RECEIVE_ADDRESS =2000 ;
    //传递的收貨地址
    String RECEIVEADDRESS_SEND_RECEIVE_ADDRESS ="RECEIVEADDRESS_SEND_RECEIVE_ADDRESS" ;
    //收货地址ID
    String RECEIVEADDRESS_ID ="RECEIVEADDRESS_ID" ;
    //保存的收货地址
    String RECEIVEADDRESS_SAVE="RECEIVEADDRESS_SAVE";
    //传递添加的收货地址的信息
    String RECEIVEADDRESS_INFO="RECEIVEADDRESS_INFO";
    //操作收货地址的方式
    String RECEIVEADDRESS_OPERATE_TYOE="RECEIVEADDRESS_OPERATE_TYOE";

    int RECEIVEADDRESS_OPERATE_ADD=2001;
    int RECEIVEADDRESS_OPERATE_DELETE=2002;
    int RECEIVEADDRESS_OPERATE_UPDATE=2003;
    int RECEIVEADDRESS_OPERATE_SELECT=2004;
}
