package com.game.config;

/**
 * Created by 74234 on 2017/5/18.
 */

public interface ConfigGame {
    int GAME_SEND_RX_CATEGORY_DETAIL_SIZEOPTION = 5001;
    int GAME_SEND_RX_CATEGORY = 5002;
    int GAME_SEND_RX_DETAIL = 5003;
    int GAME_SEND_DOWNLOAD_DOWNLOADINFO_SUCCESS=5004;

    //Download传递数据

    //Category传递数据
    String GAME_SEND_CATEGORY_TYPE = "GAME_SEND_CATEGORY_TYPE";
    String GAME_SEND_CATEGORY_TAG = "GAME_SEND_CATEGORY_TAG";
    String GAME_SEND_CATEGORY_TITLE = "GAME_SEND_CATEGORY_TITLE";
    String GAME_SEND_CATEGORY_DETAID_KID = "GAME_SEND_CATEGORY_DETAID_KID";
    String GAME_SEND_CATEGORY_DETAID_TOP = "GAME_SEND_CATEGORY_DETAID_TOP";
    String GAME_SEND_CATEGORY_DETAID_TAGID = "GAME_SEND_CATEGORY_DETAID_TAGID";
    //游戏详情页传递数据
    String GAME_SEND_GAMEDETAIL_ID="GAME_SEND_GAMEDETAIL_ID";
    String GAME_SEND_GAMEDETAIL_APPNAME="GAME_SEND_GAMEDETAIL_APPNAME";
    String GAME_SEND_GAMEDETAIL_PACKAGE="GAME_SEND_GAMEDETAIL_PACKAGE";

}
