package com.game.config;

/**
 * Created by 74234 on 2017/5/18.
 */

public interface ConfigGame {
    int GAME_SEND_RX_CATEGORY_DETAIL_SIZEOPTION=5001;
    int GAME_SEND_RX_CATEGORY =5002;
       String GAME_SEND_CATEGORY_TYPE="GAME_SEND_CATEGORY_TYPE";
    String GAME_SEND_CATEGORY_TAG="GAME_SEND_CATEGORY_TAG";
       String GAME_SEND_CATEGORY_DETAID_KID="GAME_SEND_CATEGORY_DETAID_KID";
    String GAME_SEND_CATEGORY_DETAID_TOP ="GAME_SEND_CATEGORY_DETAID_TOP";
    String GAME_SEND_CATEGORY_DETAID_TAGID ="GAME_SEND_CATEGORY_DETAID_TAGID";
}
